apiVersion: v1
kind: Service
metadata:
  name: myspringbootapp
  labels:
    app: myspringbootapp
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: myspringbootapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringbootapp
  labels:
    app: myspringbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
      - name: myspringbootapp
        image: myspringbootapp
